import DeepSeekLogo from "@/assets/deepseek.svg";

// Supported AI Providers
export const PROVIDERS = {
  "openai": {
    name: "OpenAI",
    id: "openai",
  },
  "google": {
    name: "Google",
    id: "google",
  },
  "deepseek": {
    name: "DeepSeek",
    id: "deepseek",
  },
  "openrouter": {
    name: "OpenRouter",
    id: "openrouter",
  },
  "auto": {
    name: "Auto (Best Available)",
    id: "auto",
  },
};

// Model metadata types
export type ModelSpeed = "fast" | "medium" | "slow";
export type ModelQuality = "highest" | "high" | "medium" | "balanced";
export type ModelCapability = "coding" | "general" | "multimodal";

export interface ModelMetadata {
  value: string;
  label: string;
  providers: string[];
  autoProvider: string;
  companyName: string;
  isNew?: boolean;
  logo?: string;
  // Enhanced metadata
  contextWindow?: number; // in tokens
  speed?: ModelSpeed;
  quality?: ModelQuality;
  capabilities?: ModelCapability[];
  costPer1MTokensInput?: number; // in USD
  costPer1MTokensOutput?: number; // in USD
  description?: string;
}

// Available Models
export const MODELS: ModelMetadata[] = [
  // OpenAI Models
  {
    value: "o1",
    label: "GPT-o1 (Reasoning)",
    providers: ["openai"],
    autoProvider: "openai",
    companyName: "OpenAI",
    isNew: true,
    contextWindow: 200000,
    speed: "slow",
    quality: "highest",
    capabilities: ["coding", "general"],
    costPer1MTokensInput: 15.0,
    costPer1MTokensOutput: 60.0,
    description: "Advanced reasoning model with deep thinking capabilities",
  },
  {
    value: "gpt-4o",
    label: "GPT-4o",
    providers: ["openai"],
    autoProvider: "openai",
    companyName: "OpenAI",
    contextWindow: 128000,
    speed: "medium",
    quality: "highest",
    capabilities: ["coding", "general", "multimodal"],
    costPer1MTokensInput: 5.0,
    costPer1MTokensOutput: 15.0,
    description: "Flagship multimodal model with excellent coding and reasoning capabilities",
  },
  {
    value: "gpt-4o-mini",
    label: "GPT-4o Mini",
    providers: ["openai"],
    autoProvider: "openai",
    companyName: "OpenAI",
    contextWindow: 128000,
    speed: "fast",
    quality: "high",
    capabilities: ["coding", "general"],
    costPer1MTokensInput: 0.15,
    costPer1MTokensOutput: 0.6,
    description: "Fast and affordable model with strong performance",
  },
  {
    value: "gpt-4-turbo",
    label: "GPT-4 Turbo",
    providers: ["openai"],
    autoProvider: "openai",
    companyName: "OpenAI",
    contextWindow: 128000,
    speed: "medium",
    quality: "highest",
    capabilities: ["coding", "general"],
    costPer1MTokensInput: 10.0,
    costPer1MTokensOutput: 30.0,
    description: "Previous generation flagship with proven reliability",
  },
  {
    value: "gpt-3.5-turbo",
    label: "GPT-3.5 Turbo",
    providers: ["openai"],
    autoProvider: "openai",
    companyName: "OpenAI",
    contextWindow: 16385,
    speed: "fast",
    quality: "medium",
    capabilities: ["coding", "general"],
    costPer1MTokensInput: 0.5,
    costPer1MTokensOutput: 1.5,
    description: "Fast and economical model for simple tasks",
  },
  // Google Models
  {
    value: "gemini-2.0-flash-exp",
    label: "Gemini 2.0 Flash (Experimental)",
    providers: ["google"],
    autoProvider: "google",
    companyName: "Google",
    isNew: true,
    contextWindow: 1000000,
    speed: "fast",
    quality: "high",
    capabilities: ["coding", "general", "multimodal"],
    costPer1MTokensInput: 0.0,
    costPer1MTokensOutput: 0.0,
    description: "Latest experimental Gemini model - free during preview",
  },
  {
    value: "gemini-1.5-pro",
    label: "Gemini 1.5 Pro",
    providers: ["google"],
    autoProvider: "google",
    companyName: "Google",
    contextWindow: 2000000,
    speed: "medium",
    quality: "highest",
    capabilities: ["coding", "general", "multimodal"],
    costPer1MTokensInput: 1.25,
    costPer1MTokensOutput: 5.0,
    description: "Most capable Google model with massive 2M token context window",
  },
  {
    value: "gemini-1.5-flash",
    label: "Gemini 1.5 Flash",
    providers: ["google"],
    autoProvider: "google",
    companyName: "Google",
    contextWindow: 1000000,
    speed: "fast",
    quality: "high",
    capabilities: ["coding", "general", "multimodal"],
    costPer1MTokensInput: 0.075,
    costPer1MTokensOutput: 0.3,
    description: "Fast and efficient model for most tasks",
  },
  // DeepSeek Models
  {
    value: "deepseek-coder",
    label: "DeepSeek Coder",
    providers: ["deepseek"],
    autoProvider: "deepseek",
    logo: DeepSeekLogo,
    companyName: "DeepSeek",
    contextWindow: 128000,
    speed: "fast",
    quality: "high",
    capabilities: ["coding"],
    costPer1MTokensInput: 0.14,
    costPer1MTokensOutput: 0.28,
    description: "Specialized model for code generation and analysis",
  },
  {
    value: "deepseek-chat",
    label: "DeepSeek Chat",
    providers: ["deepseek"],
    autoProvider: "deepseek",
    logo: DeepSeekLogo,
    companyName: "DeepSeek",
    contextWindow: 128000,
    speed: "fast",
    quality: "high",
    capabilities: ["coding", "general"],
    costPer1MTokensInput: 0.14,
    costPer1MTokensOutput: 0.28,
    description: "Versatile model for chat and coding tasks",
  },
  // OpenRouter Models (Multi-provider access)
  {
    value: "anthropic/claude-sonnet-4.5",
    label: "Claude Sonnet 4.5",
    providers: ["openrouter"],
    autoProvider: "openrouter",
    companyName: "Anthropic (via OpenRouter)",
    isNew: true,
    contextWindow: 200000,
    speed: "medium",
    quality: "highest",
    capabilities: ["coding", "general"],
    costPer1MTokensInput: 3.0,
    costPer1MTokensOutput: 15.0,
    description: "#1 most popular - Balanced Claude model with excellent reasoning",
  },
  {
    value: "anthropic/claude-opus-4.5",
    label: "Claude Opus 4.5",
    providers: ["openrouter"],
    autoProvider: "openrouter",
    companyName: "Anthropic (via OpenRouter)",
    contextWindow: 200000,
    speed: "slow",
    quality: "highest",
    capabilities: ["coding", "general"],
    costPer1MTokensInput: 15.0,
    costPer1MTokensOutput: 75.0,
    description: "Most capable Claude model for complex tasks",
  },
  {
    value: "xiaomi/mimo-v2-flash:free",
    label: "MiMo-V2-Flash (Free)",
    providers: ["openrouter"],
    autoProvider: "openrouter",
    companyName: "Xiaomi (via OpenRouter)",
    isNew: true,
    contextWindow: 128000,
    speed: "fast",
    quality: "high",
    capabilities: ["coding", "general"],
    costPer1MTokensInput: 0.0,
    costPer1MTokensOutput: 0.0,
    description: "#2 most popular - Free Xiaomi model with strong performance",
  },
  {
    value: "x-ai/grok-code-fast-1",
    label: "Grok Code Fast 1",
    providers: ["openrouter"],
    autoProvider: "openrouter",
    companyName: "xAI (via OpenRouter)",
    isNew: true,
    contextWindow: 131072,
    speed: "fast",
    quality: "high",
    capabilities: ["coding"],
    costPer1MTokensInput: 5.0,
    costPer1MTokensOutput: 15.0,
    description: "#3 most popular - Specialized Grok model for fast code generation",
  },
  {
    value: "google/gemini-3-flash-preview",
    label: "Gemini 3 Flash Preview",
    providers: ["openrouter"],
    autoProvider: "openrouter",
    companyName: "Google (via OpenRouter)",
    isNew: true,
    contextWindow: 1000000,
    speed: "fast",
    quality: "highest",
    capabilities: ["coding", "general", "multimodal"],
    costPer1MTokensInput: 0.075,
    costPer1MTokensOutput: 0.3,
    description: "#4 most popular - Next-gen Google model with massive context",
  },
  {
    value: "deepseek/deepseek-v3.2",
    label: "DeepSeek V3.2",
    providers: ["openrouter"],
    autoProvider: "openrouter",
    companyName: "DeepSeek (via OpenRouter)",
    isNew: true,
    contextWindow: 128000,
    speed: "fast",
    quality: "high",
    capabilities: ["coding"],
    costPer1MTokensInput: 0.14,
    costPer1MTokensOutput: 0.28,
    description: "#5 most popular - Latest DeepSeek model for code",
  },
  {
    value: "google/gemini-2.0-flash-exp:free",
    label: "Gemini 2.0 Flash (OR Free)",
    providers: ["openrouter"],
    autoProvider: "openrouter",
    companyName: "Google (via OpenRouter)",
    isNew: true,
    contextWindow: 1000000,
    speed: "fast",
    quality: "high",
    capabilities: ["coding", "general", "multimodal"],
    costPer1MTokensInput: 0.0,
    costPer1MTokensOutput: 0.0,
    description: "Free Gemini 2.0 Flash via OpenRouter",
  },
  {
    value: "google/gemini-2.5-flash",
    label: "Gemini 2.5 Flash",
    providers: ["openrouter"],
    autoProvider: "openrouter",
    companyName: "Google (via OpenRouter)",
    contextWindow: 1000000,
    speed: "fast",
    quality: "high",
    capabilities: ["coding", "general", "multimodal"],
    costPer1MTokensInput: 0.075,
    costPer1MTokensOutput: 0.3,
    description: "#7 most popular - Fast Gemini model",
  },
  {
    value: "google/gemini-2.5-pro",
    label: "Gemini 2.5 Pro",
    providers: ["openrouter"],
    autoProvider: "openrouter",
    companyName: "Google (via OpenRouter)",
    contextWindow: 2000000,
    speed: "medium",
    quality: "highest",
    capabilities: ["coding", "general", "multimodal"],
    costPer1MTokensInput: 1.25,
    costPer1MTokensOutput: 5.0,
    description: "#8 most popular - Pro Gemini model with 2M context",
  },
  {
    value: "x-ai/grok-4.1-fast",
    label: "Grok 4.1 Fast",
    providers: ["openrouter"],
    autoProvider: "openrouter",
    companyName: "xAI (via OpenRouter)",
    contextWindow: 131072,
    speed: "fast",
    quality: "high",
    capabilities: ["coding", "general"],
    costPer1MTokensInput: 5.0,
    costPer1MTokensOutput: 15.0,
    description: "#9 most popular - Latest Grok model",
  },
  {
    value: "google/gemini-2.5-flash-lite",
    label: "Gemini 2.5 Flash Lite",
    providers: ["openrouter"],
    autoProvider: "openrouter",
    companyName: "Google (via OpenRouter)",
    contextWindow: 1000000,
    speed: "fast",
    quality: "medium",
    capabilities: ["coding", "general"],
    costPer1MTokensInput: 0.0375,
    costPer1MTokensOutput: 0.15,
    description: "#10 most popular - Lightweight Gemini for simple tasks",
  },
  {
    value: "xiaomi/mimo-v2-flash",
    label: "MiMo V2 Flash",
    providers: ["openrouter"],
    autoProvider: "openrouter",
    companyName: "Xiaomi (via OpenRouter)",
    contextWindow: 32768,
    speed: "fast",
    quality: "medium",
    capabilities: ["coding", "general"],
    costPer1MTokensInput: 0.1,
    costPer1MTokensOutput: 0.1,
    description: "Affordable Chinese model with decent performance",
  },
];
